// system-design/books-store/frontend/angular/src/app/books/books-list/books-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Author, Book } from 'src/app/books/book.model';
import { BookService } from 'src/app/books/book.service';
import { AuthorConcatenationPipe } from 'src/app/books/authors-concatenation.pipe';

@Component({
  selector: 'app-books-list',
  standalone: true,
  imports: [CommonModule, RouterModule, AuthorConcatenationPipe],
  templateUrl: './books-list.component.html',
  styleUrl: './books-list.component.css',
})
export class BooksListComponent implements OnInit {
  books?: Book[];

  constructor(private bookService: BookService) { }

  ngOnInit(): void {
    this.bookService.getAll().subscribe(books => {
      this.books = books;
    });
  }

  formatAuthor(author: Author): string
  {
      return `${author.firstName} ${author.lastName}`;
  
  }

}

<ul class="books">
    <li *ngFor="let book of books">
        <div class="card mb-3 border-white" style="max-width: 680px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img class="img-fluid rounded-start" [src]="book?.thumbnailUrl" alt="{{ book?.title }}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ book?.title }}
                        </h5>
                        <div class="card-text">
                            ISBN: {{ book?.isbn }}
                        </div>
                        <div class="card-text">
                            Authors: {{ book.authors | authorsConcatenation }}
                        </div>
                        <p class="card-text">
                            <small class="text-muted">
                                Last updated 3 mins ago
                            </small>
                        </p>

                        <a [routerLink]="['/book', book?.id]" routerLinkActive="active" ariaCurrentWhenActive="page">View</a>

                        <!-- <a class="card-link" href="#">Book</a> -->
                    </div>
                </div>
            </div>
        </div>


        <!-- <div>
            <a routerLink="['/book', book?.id]">
                <span>
                    <img class="thumbnail" [src]="book?.thumbnailUrl" alt="{{ book?.title }}" />
                </span>
                <span>
                    <p>{{ book?.title }}</p>
                </span>
            </a>
        </div> -->
    </li>
</ul>

// system-design/books-store/frontend/react/src/app/components/books/books-list/books-list.tsx
import React from 'react';
import { Link } from "react-router-dom";
import BooksService from '../books.service';
import styles from './books-list.module.css';
import { Book } from '../book.model';

/* eslint-disable-next-line */
export interface BooksListProps {
  readonly booksService: BooksService
}

interface BooksState {
  readonly books: Book[]
}

export class BooksList extends React.Component<BooksListProps, BooksState> {

  constructor(props: BooksListProps) {
    super(props);
    this.state = { books: [] };
  }

  componentDidMount() {
    this.props.booksService.getAll().subscribe((books: Book[]) => {
      this.setState({ books });
    });  
  }

  render() {
    const { books } = this.state

    
    const booksList = books.map((book) => (
      <li key={book.id}>
        <div className="card mb-3 border-white" style={{maxWidth: '680px'}}>
            <div className="row g-0">
                <div className="col-md-4">
                    <img className="img-fluid rounded-start" src={book?.thumbnailUrl} alt="{book?.title}" />
                </div>
                <div className="col-md-8">
                    <div className="card-body">
                        <h5 className="card-title">
                            {book?.title}
                        </h5>
                        <div className="card-text">
                            ISBN: {book?.isbn}
                        </div>
                        <div className="card-text">
                            Language: {book?.language}
                        </div>
                        <div className="card-text">
                            Authors: {book.authors.map((author) => `${author?.firstName} ${author?.lastName}`).join(', ')}
                        </div>
                        <Link to={'/books/' + book?.id}>View</Link>
                    </div>
                </div>
            </div>
        </div>
      </li>
    ));

    return (
      <div>
        <ul className={styles.books}>{booksList}</ul>
      </div>
    );
  }
}


// export class BooksList extends React.Component<BooksListProps, BooksState> {

//   constructor(props: BooksListProps) {
//     super(props)

//     props.booksService.getAll().subscribe((books: Book[]) => {
//       // const xstate: BooksState = { books };
//       // this.state = xstate;
//       this.state = { books };
//     });
//   }

//   render() {
//     const booksList = this.state.books.map((book) => (
//       <li key={book.id}>
//         {book.title}
//       </li>
//     ));

//     return (
//       <div className={styles['container']}>
//         <ul>{booksList}</ul>
//         <pre>{JSON.stringify(this.state.books, null, 2)}</pre>
//       </div>
//     );
//   }
// }

export default BooksList;
