// system-design/books-store/frontend/angular/src/app/books/book-detail/book-details.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { Book } from 'src/app/books/book.model';
import { BookService } from 'src/app/books/book.service';
import { AuthorConcatenationPipe } from '../authors-concatenation.pipe';

@Component({
  selector: 'app-book-details',
  standalone: true,
  imports: [CommonModule, AuthorConcatenationPipe],
  templateUrl: './book-details.component.html',
  styleUrl: './book-details.component.css',
})
export class BookDetailsComponent implements OnInit {
  bookDetails?: Book;

  constructor(
    private route: ActivatedRoute, 
    private bookService: BookService) { }

  ngOnInit() {
    this.route.paramMap.subscribe(params => {
      let bookId = Number(params.get('id'));
      this.bookService.get(bookId).subscribe(book => this.bookDetails = book);
    });
  }
}

<div class="card mb-3 border-white" style="max-width: 680px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img class="img-fluid rounded-start" [src]="bookDetails?.thumbnailUrl" alt="{{ bookDetails?.title }}">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">
                    {{ bookDetails?.title }}
                </h5>
                <div class="card-text">
                    ISBN: {{ bookDetails?.isbn }}
                </div>
                <div class="card-text">
                    Authors: {{ bookDetails?.authors| authorsConcatenation }}
                </div>

                <p class="card-text">
                    <small class="text-muted">
                        Last updated 3 mins ago
                    </small>
                </p>

            </div>
        </div>
    </div>
</div>

// system-design/books-store/frontend/react/src/app/components/books/book-details/book-details.tsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Book } from '../book.model';
import BooksService from '../books.service';
import styles from './book-details.module.css';

/* eslint-disable-next-line */
export interface BookDetailsProps {
  readonly booksService: BooksService;
}

export default function BookDetails(props: {booksService: BooksService}) {
  const [book, setBook] = useState<Book | null>(null);
  const { id } = useParams();

  useEffect(() => {
    props.booksService.get(Number(id)).subscribe((book: Book) => {
      setBook(book);
    });
  }, [id]);

  return (
    <div className={styles['container']}>
      <div className="card mb-3 border-white" style={{ maxWidth: '680px' }}>
        <div className="row g-0">
          <div className="col-md-4">
            <img
              className="img-fluid rounded-start"
              src={book?.thumbnailUrl}
              alt="{book?.title}"
            />
          </div>
          <div className="col-md-8">
            <div className="card-body">
              <h5 className="card-title">{book?.title}</h5>
              <div className="card-text">ISBN: {book?.isbn}</div>
              <div className="card-text">Language: {book?.language}</div>
              <div className="card-text">
                Authors:{' '}
                {book?.authors
                  .map((author) => `${author?.firstName} ${author?.lastName}`)
                  .join(', ')}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// export default BookDetails;
